stroke_width:
  default: medium
  type: enum
  refresh: true
  choices:
    - extra-thin
    - thin
    - medium
    - thick
    - extra-thick
ignored_icons:
  default: "d-liked|square-full|circle"
  type: list
  list_type: compact
  refresh: true
