stroke_width:
  default: medium
  type: enum
  refresh: true
  choices:
    - extra-thin
    - thin
    - medium
    - thick
    - extra-thick
ignored_mappings:
  default: ""
  type: list
  list_type: compact
  refresh: true