import { apiInitializer } from "discourse/lib/api";

export default apiInitializer((api) => {
  // Configure stroke width
  const strokeWidthMap = {
    "extra-thin": "1",
    "thin": "1.5",
    "medium": "2",
    "thick": "2.5",
    "extra-thick": "3",
  };

  document.documentElement.style.setProperty(
    "--lucide-icons-stroke-width",
    strokeWidthMap[settings.stroke_width] || "2"
  );

  const iconMappings = {
    // Standard icons
    "align-left": "lc-align-left",
    "anchor": "lc-anchor",
    "asterisk": "lc-asterisk",
    "ban": "lc-ban",
    "bed": "lc-bed",
    "bell": "lc-bell",
    "bold": "lc-bold",
    "book": "lc-book",
    "bookmark": "lc-bookmark",
    "briefcase": "lc-briefcase",
    "chart-bar": "lc-chart-bar",
    "chart-pie": "lc-chart-pie",
    "check": "lc-check",
    "circle-check": "lc-circle-check",
    "circle-chevron-down": "lc-circle-chevron-down",
    "circle-minus": "lc-circle-minus",
    "circle-plus": "lc-circle-plus",
    "circle-user": "lc-circle-user",
    "clock": "lc-clock",
    "code": "lc-code",
    "copy": "lc-copy",
    "download": "lc-download",
    "file": "lc-file",
    "flag": "lc-flag",
    "folder": "lc-folder",
    "folder-open": "lc-folder-open",
    "gift": "lc-gift",
    "globe": "lc-globe",
    "heart": "lc-heart",
    "house": "lc-house",
    "id-card": "lc-id-card",
    "image": "lc-image",
    "images": "lc-images",
    "inbox": "lc-inbox",
    "italic": "lc-italic",
    "key": "lc-key",
    "keyboard": "lc-keyboard",
    "link": "lc-link",
    "list": "lc-list",
    "list-check": "lc-list-check",
    "lock": "lc-lock",
    "minus": "lc-minus",
    "moon": "lc-moon",
    "paintbrush": "lc-paintbrush",
    "palette": "lc-palette",
    "pause": "lc-pause",
    "pencil": "lc-pencil",
    "play": "lc-play",
    "plug": "lc-plug",
    "plus": "lc-plus",
    "power-off": "lc-power-off",
    "reply": "lc-reply",
    "rocket": "lc-rocket",
    "scroll": "lc-scroll",
    "share": "lc-share",
    "shuffle": "lc-shuffle",
    "signal": "lc-signal",
    "square-check": "lc-square-check",
    "square-plus": "lc-square-plus",
    "star": "lc-star",
    "sun": "lc-sun",
    "table": "lc-table",
    "tag": "lc-tag",
    "tags": "lc-tags",
    "upload": "lc-upload",
    "user": "lc-user",
    "user-check": "lc-user-check",
    "user-pen": "lc-user-pen",
    "user-plus": "lc-user-plus",
    "wrench": "lc-wrench",

    // Arrows & Chevrons
    "angle-down": "lc-chevron-down",
    "angle-left": "lc-chevron-left",
    "angle-right": "lc-chevron-right",
    "angle-up": "lc-chevron-up",
    "angles-down": "lc-chevrons-down",
    "angles-left": "lc-chevrons-left",
    "angles-right": "lc-chevrons-right",
    "angles-up": "lc-chevrons-up",
    "arrow-down": "lc-arrow-down",
    "arrow-left": "lc-arrow-left",
    "arrow-line-left": "lc-arrow-left-from-line",
    "arrow-line-right": "lc-arrow-right-from-line",
    "arrow-right": "lc-arrow-right",
    "arrow-rotate-left": "lc-rotate-ccw",
    "arrow-rotate-right": "lc-rotate-cw",
    "arrow-up": "lc-arrow-up",
    "arrows-rotate": "lc-refresh-ccw",
    "caret-down": "lc-chevron-down",
    "caret-left": "lc-chevron-left",
    "caret-right": "lc-chevron-right",
    "caret-up": "lc-chevron-up",
    "chevron-down": "lc-chevron-down",
    "chevron-left": "lc-chevron-left",
    "chevron-right": "lc-chevron-right",
    "chevron-up": "lc-chevron-up",

    // Icons with different names
    "at": "lc-at-sign",
    "backward": "lc-rewind",
    "backward-fast": "lc-skip-back",
    "backward-step": "lc-step-back",
    "bars": "lc-menu",
    "bars-staggered": "lc-menu",
    "bell-slash": "lc-bell-off",
    "book-open-reader": "lc-book-open-text",
    "bookmark-delete": "lc-bookmark-x",
    "box-archive": "lc-archive",
    "bullseye": "lc-target",
    "calendar-day": "lc-calendar-days",
    "category": "lc-lock",
    "certificate": "lc-award",
    "circle-exclamation": "lc-circle-alert",
    "circle-info": "lc-info",
    "circle-question": "lc-circle-help",
    "circle-xmark": "lc-circle-x",
    "cloud-arrow-down": "lc-cloud-download",
    "cloud-arrow-up": "lc-cloud-upload",
    "comment": "lc-message-square",
    "compress": "lc-minimize",
    "crosshairs": "lc-crosshair",
    "cube": "lc-cuboid",
    "desktop": "lc-monitor",
    "earth-americas": "lc-globe",
    "ellipsis": "lc-ellipsis",
    "ellipsis-vertical": "lc-ellipsis-vertical",
    "envelope": "lc-mail",
    "face-smile": "lc-smile",
    "file-lines": "lc-file-text",
    "filter": "lc-funnel",
    "flask": "lc-flask-conical",
    "font": "lc-type",
    "forward": "lc-skip-forward",
    "forward-fast": "lc-fast-forward",
    "forward-step": "lc-step-forward",
    "gavel": "lc-gavel",
    "gear": "lc-settings",
    "grip-lines": "lc-grip-horizontal",
    "handshake-angle": "lc-handshake",
    "hashtag": "lc-hash",
    "hourglass-start": "lc-hourglass",
    "language": "lc-languages",
    "layer-group": "lc-layers",
    "left-right": "lc-arrow-left-right",
    "like": "lc-heart",
    "link-slash": "lc-link-2-off",
    "list-ol": "lc-list-ordered",
    "list-ul": "lc-list",
    "location-dot": "lc-map-pin",
    "magnifying-glass": "lc-search",
    "magnifying-glass-minus": "lc-zoom-out",
    "magnifying-glass-plus": "lc-zoom-in",
    "mobile-screen-button": "lc-smartphone",
    "paper-plane": "lc-send",
    "puzzle-piece": "lc-puzzle",
    "quote-left": "lc-quote",
    "quote-right": "lc-quote",
    "right-from-bracket": "lc-log-out",
    "right-to-bracket": "lc-log-in",
    "robot": "lc-bot",
    "rotate": "lc-rotate-ccw",
    "shield-halved": "lc-shield-half",
    "sliders": "lc-sliders-horizontal",
    "spinner": "lc-loader",
    "temperature-three-quarters": "lc-thermometer",
    "thumbtack": "lc-pin",
    "toggle-off": "lc-toggle-left",
    "toggle-on": "lc-toggle-right",
    "trash-can": "lc-trash",
    "triangle-exclamation": "lc-triangle-alert",
    "truck-medical": "lc-ambulance",
    "unlock": "lc-lock-open",
    "unlock-keyhole": "lc-lock-keyhole-open",
    "up-down": "lc-arrow-up-down",
    "up-right-from-square": "lc-external-link",
    "user-gear": "lc-user-cog",
    "user-group": "lc-users",
    "user-xmark": "lc-user-x",
    "wand-magic": "lc-wand-sparkles",
    "xmark": "lc-x",

    // Brand icons
    "fab-apple": "lc-apple",
    "fab-chrome": "lc-chromium",
    "fab-facebook": "lc-facebook",
    "fab-github": "lc-github",
    "fab-instagram": "lc-instagram",
    "fab-linkedin-in": "lc-linkedin",
    "fab-twitter": "lc-twitter",

    // FontAwesome Regular variants (far-)
    "far-bell": "lc-bell",
    "far-bell-slash": "lc-bell-off",
    "far-calendar-plus": "lc-calendar-plus",
    "far-chart-bar": "lc-chart-bar",
    "far-circle": "lc-circle",
    "far-circle-dot": "lc-circle-dot",
    "far-clipboard": "lc-clipboard",
    "far-clock": "lc-clock",
    "far-comment": "lc-message-square",
    "far-comments": "lc-messages-square",
    "far-copyright": "lc-copyright",
    "far-envelope": "lc-mail",
    "far-eye": "lc-eye",
    "far-eye-slash": "lc-eye-off",
    "far-face-frown": "lc-frown",
    "far-face-meh": "lc-meh",
    "far-face-smile": "lc-smile",
    "far-file-lines": "lc-file-text",
    "far-heart": "lc-heart",
    "far-image": "lc-image",
    "far-moon": "lc-moon",
    "far-square-check": "lc-square-check",
    "far-star": "lc-star",
    "far-sun": "lc-sun",
    "far-thumbs-down": "lc-thumbs-down",
    "far-thumbs-up": "lc-thumbs-up",
    "far-trash-can": "lc-trash",

    // Discourse icons
    "d-chat": "lc-message-square-text",
    "d-drop-collapsed": "lc-chevron-right",
    "d-drop-expanded": "lc-chevron-down",
    "d-liked": "lc-heart",
    "d-muted": "lc-bell-off",
    "d-post-share": "lc-link",
    "d-regular": "lc-bell",
    "d-tracking": "lc-bell",
    "d-unliked": "lc-heart",
    "d-watching": "lc-bell",
    "d-watching-first": "lc-bell",
    "discourse-compress": "lc-minimize",
    "discourse-expand": "lc-maximize",
    "discourse-other-tab": "lc-grid-2x2",

    // Notification icons
    "notification.assigned": "lc-user-check",
    "notification.bookmark_reminder": "lc-clock",
    "notification.chat_quoted": "lc-message-square",
    "notification.discourse_assign.assign_group_notification": "lc-users",
    "notification.edited": "lc-pen",
    "notification.granted_badge": "lc-award",
    "notification.group_mentioned": "lc-users",
    "notification.group_message_summary": "lc-users",
    "notification.invited_to_private_message": "lc-mail",
    "notification.invited_to_topic": "lc-arrow-right",
    "notification.invitee_accepted": "lc-user-plus",
    "notification.liked": "lc-heart",
    "notification.liked_2": "lc-heart",
    "notification.liked_consolidated": "lc-heart",
    "notification.liked_many": "lc-heart",
    "notification.linked": "lc-link",
    "notification.membership_request_accepted": "lc-user-plus",
    "notification.membership_request_consolidated": "lc-users",
    "notification.mentioned": "lc-at-sign",
    "notification.moved_post": "lc-move",
    "notification.post_approved": "lc-check",
    "notification.posted": "lc-reply",
    "notification.private_message": "lc-mail",
    "notification.quoted": "lc-quote",
    "notification.reaction": "lc-bell",
    "notification.replied": "lc-reply",
    "notification.topic_reminder": "lc-clock",
    "notification.votes_released": "lc-plus",
    "notification.watching_first_post": "lc-bell",

    // User menu icons
    "user_menu.drafts": "lc-pencil",
    "user_menu.replies": "lc-reply",

    // Topic state icons
    "topic.closed": "lc-lock",
  };

  Object.entries(iconMappings).forEach(([faIcon, lucideIcon]) => {
    api.replaceIcon(faIcon, lucideIcon);
  });
});
